language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-8
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8

    - os: linux
      dist: xenial
      compiler: clang

before_install:
- eval "${MATRIX_EVAL}"

before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../task_about_circles
  - make -j
  - ./CircleTest/CircleTest
notifications:
  email: false