language: cpp

compiler:
  - gcc
  - clang

before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../task_about_circles
  - make -j
  - ./CircleTest/CircleTest
notifications:
  email: false